[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fiddlesticks"
description = "Password recovery tool for encrypted archives (currently only .7z files supported)."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "James Parrott", email = "james@jamesparrott.dev" }
]
requires-python = ">=3.12"
dynamic=["version"]

dependencies = []

[project.urls]
GitHub = "https://github.com/Hazardous-Area/fiddlesticks"

[project.scripts]
fiddlesticks = "fiddlesticks:cli"

[project.optional-dependencies]
py7zr = [
    "py7zr",
]
aegis = [
    "py-avdu",
]
keepassxc = [
    "pykeepass",
]

[dependency-groups]
dev = [
    {include-group = "lint"},
    {include-group = "test"},
]
test = [
    "fiddlesticks[py7zr,aegis,keepassxc]",
    "pytest",
    "hypothesis",
]
lint = [
    "ruff",
    "ty",
    "pre-commit",
]



[tool.hatch.build.targets.wheel]
only-include = ["src"]
sources = {"src" = ""}  # move from "src" directory for wheel

[tool.hatch.version]
path = "src/fiddlesticks.py" 

[tool.pytest.ini_options]
markers = [
    "slow: marks other tests that cause bottlenecks",
    "hypothesis: tests that require hypothesis",
]
python_files = "test_*.py *_test.py *_tests.py"

