[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fiddlesticks"
description = "Password recovery tool for encrypted files (.7z archives .kdbx files, and Aegis archives)."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "James Parrott", email = "james@jamesparrott.dev" }
]
requires-python = ">=3.13"

# Define the version statically here, not with dynamic=["version"], so that
# the fiddlesticks.py needn't be copied into the the Docker image in order to
# install the dependencies and test dependency group
version = "0.6.1" 

dependencies = []

[project.urls]
GitHub = "https://github.com/Hazardous-Area/fiddlesticks"

[project.scripts]
fiddlesticks = "fiddlesticks:cli"

[project.optional-dependencies]
ssh = [
    "cryptography>=47", # For "incorrect PW" error message from Rust code
    "bcrypt",
]
keepassxc = [
    "pykeepass",
]
aegis = [
    "py-avdu",
]
py7zr = [
    "py7zr",
]
msoffice = [
    "msoffcrypto-tool",
]
all = [
    "fiddlesticks[ssh,keepassxc,aegis,py7zr,msoffice]",
]
# Note.  Some features also require optional dependencies 
# that are not available on PyPi (and must be installed from
# elsewhere, e.g. from packages.ubuntu.com):
# - 7zip
# - veracrypt


[dependency-groups]
all_optional_deps = [
        "fiddlesticks[ssh,keepassxc,aegis,py7zr,msoffice]",
]
dev = [
    {include-group= "all_optional_deps"},
    {include-group = "lint"},
    {include-group = "test"},
]
test = [
    "pytest",
    "hypothesis",
    "coverage>=7.13",
    "covdefaults",
]
lint = [
    "ruff",
    "ty",
    "pre-commit",
]



[tool.hatch.build.targets.wheel]
only-include = ["src"]
sources = {"src" = ""}  # move from "src" directory for wheel

[tool.hatch.version]
path = "src/fiddlesticks.py" 

[tool.pytest.ini_options]
markers = [
    "slow: marks other tests that cause bottlenecks",
    "hypothesis: tests that require hypothesis",
]
python_files = "test_*.py *_test.py *_tests.py"

[tool.coverage.run]
concurrency = ["multiprocessing"]
source = ["src"]
omit = ["tests/*"]
patch = ["subprocess"]
plugins = [
    "covdefaults",
]
