name: Benchmarks

on:
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-26.04
    container:
      image: ghcr.io/hazardous-area/fiddlesticks/test_env:sha-f1100e7
      # Extra options needed for Veracrypt to 
      # mount volumes inside a Docker container
      options: >-
        --device /dev/fuse
        --cap-add SYS_ADMIN
        --security-opt apparmor:unconfined
        --privileged
        -v /dev:/dev
    steps:
    - name: Check out repo
      uses: actions/checkout@v7

    - name: Install code under test
      run: |
        . /fiddlesticks/.venv/bin/activate
        pip install -e .[all]   

    - name: Run Benchmarks
      run: |
        . /fiddlesticks/.venv/bin/activate
        python benchmarks.py --output-file benchmarks.txt --max-time-s=3540 --max-num-subs=8 --num-cores=4

    - name: Print Benchmark results file
      run: |
        cat benchmarks.txt
