name: Run pre-commit hooks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        version: 0.12.7
        python-version: "3.14"

    - name: uv Sync project with all dependency groups (for type checker)
      run: uv sync --group dev

    - name: Run pre-commit
      run: uv run pre-commit run --all-files --show-diff-on-failure --color=always
      shell: bash