name: Run pre-commit hooks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-26.04
    container:
      image: ghcr.io/hazardous-area/fiddlesticks/test_env:sha-f1100e7
      # Extra options needed for Veracrypt to 
      # mount volumes inside a Docker container
      options: >-
        --device /dev/fuse
        --cap-add SYS_ADMIN
        --security-opt apparmor:unconfined
        --privileged
        -v /dev:/dev
    steps:
    - name: Check out repo
      uses: actions/checkout@v7

    - name: Install project deps and lint group
      run: |
        . /fiddlesticks/.venv/bin/activate
        pip install --group=lint --group=test
        pip install -e .[all] --only-deps

    - name: Run Ruff
      run: /fiddlesticks/.venv/bin/ruff check

    - name: Run Ty
      env:
        VIRTUAL_ENV: /fiddlesticks/.venv
      run: /fiddlesticks/.venv/bin/ty check
