name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v7
    
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.14"
    
    - name: Install dependencies
      run: |
        pip install -e . --group=test

    - name: Run PyTest
      run: |
        pytest -rA --tb=short