name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v7
    
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.14"
    

    - name: Check Git hasn't corrupted test data files
      run: |
        sha256sum tests/data_files/Test_vault_Do_Not_Use.kdbx

    - name: Install Veracrypt from unit193's apt repo
      run: |
        sudo add-apt-repository ppa:unit193/encryption
        sudo apt update
        sudo apt install veracrypt

    - name: Create venv
      run: |
        python3 -m venv .venv

    - name: Install dependencies
      run: |
        . ./.venv/bin/activate
        pip install -e . --group=test

    - name: Run PyTest (via Coverage)
      run: |
        . ./.venv/bin/activate
        coverage run -m pytest -rA -vv --tb=short tests && coverage combine && coverage report